services:
  postgres:
    image: postgres:17-alpine
    container_name: roomiesync-postgres-db
    environment:
      POSTGRES_DB: RoomieSync
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - roomiesync-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roomiesync-springboot-app
    depends_on:
      - postgres
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - roomiesync-network

volumes:
  postgres-data:

networks:
  roomiesync-network:
    driver: bridge