services:
  postgres:
    image: postgres:17-alpine
    container_name: roomiesync-postgres-db
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - roomiesync-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roomiesync-springboot-app
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: ${PGDATABASE}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "8080:8080"
    networks:
      - roomiesync-network
      
volumes:
  postgres-data:

networks:
  roomiesync-network:
    driver: bridge